// apps/vue-app/src/pages/index/index.vue
<template>
  <view class="demo">
    <component 
      v-for="(item, index) in data" 
      :key="index" 
      :is="item.component" 
      v-bind="item.props" 
    >
    <template #item="{ data }">
      <view style="color: red;">
        <comp3 :label="data"></comp3>
      </view>
    </template>
   </component>

   <nut-button @tap="onAdd">添加</nut-button>
  </view>
</template>

<script setup>
import { ref } from "vue";
import comp1 from "../../components/comp1/comp1.vue";
import comp2 from "../../components/comp2/comp2.vue";
import comp3 from "../../components/comp3/comp3.vue";

const data = ref([
  { component: comp1, props: { label: "COMP1" } },
  { component: comp2, props: { label: "COMP2" } }
])

function onAdd(e) {
  data.value.push({ component: comp3, props: { label: "COMP1" } })
}

</script>

<style>
.demo {
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
</style>

// apps/react-app/src/pages/index/index.tsx
import React from "react";
import { View } from "@tarojs/components";
import { Button } from "@nutui/nutui-react-taro";
import "./index.scss";
import Comp1 from "../../components/comp1/comp1";

function Index() {
  const [data, setData] = React.useState([] as any);
  React.useEffect(() => {
    setData([
      {
        component: Comp1,
        props: {
          label: "hello",
        },
      },
      {
        component: Comp1,
        props: {
          label: "hello2",
        },
      },
    ]);
  }, [data]);
  return (
    <View className="nutui-react-demo">
      {/* <View className="index">欢迎使用 NutUI React 开发 Taro 多端项目。</View>
      <View className="index">
        <Button type="primary" className="btn">
          NutUI React Button
        </Button>
      </View> */}
      <View>
        {data.map((item: any, index: number) => {
          const Comp = item.component;
          return (
            <Comp
              key={index}
              {...item.props}
              slot={(label: any) => {
                return <View style={{ color: "red" }}>{label}</View>;
              }}
            />
          );
        })}
      </View>
    </View>
  );
}

export default Index;
